package integration

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// GithubClient handles communication with GitHub REST API.
type GithubClient struct {
	Token      string
	HTTPClient *http.Client
	Username   string
}

// NewGithubClient creates a new GitHub client.
func NewGithubClient(token string) *GithubClient {
	return &GithubClient{
		Token:      token,
		HTTPClient: &http.Client{},
	}
}

// SyncRepository creates a private repository on GitHub, returning the repository URL.
func (c *GithubClient) SyncRepository(repoName string) (string, error) {
	if c.Token == "" {
		return "", fmt.Errorf("GITHUB_TOKEN is not configured")
	}

	// Fetch username if not cached
	if c.Username == "" {
		reqUser, _ := http.NewRequest("GET", "https://api.github.com/user", nil)
		reqUser.Header.Set("Authorization", "Bearer "+c.Token)
		respUser, err := c.HTTPClient.Do(reqUser)
		if err == nil && respUser.StatusCode == 200 {
			var userData struct {
				Login string `json:"login"`
			}
			bodyUser, _ := io.ReadAll(respUser.Body)
			json.Unmarshal(bodyUser, &userData)
			c.Username = userData.Login
			respUser.Body.Close()
		} else {
			if respUser != nil {
				respUser.Body.Close()
			}
			c.Username = "truonglv4" // fallback
		}
	}

	url := "https://api.github.com/user/repos"
	payload := map[string]interface{}{
		"name":        repoName,
		"description": "Auto-generated by AI Agent",
		"private":     true,
	}

	body, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", url, bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+c.Token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to create github repository: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 422 {
		// 422 often means "name already exists on this account", we can just reuse the existing repo.
		return fmt.Sprintf("https://github.com/%s/%s", c.Username, repoName), nil
	}
	if resp.StatusCode >= 300 {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("github repository creation failed (status %d): %s", resp.StatusCode, string(b))
	}

	var data struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return "", fmt.Errorf("failed to decode github response: %w", err)
	}

	return data.HTMLURL, nil
}
