package integration

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// TaskPayload represents a parsed subtask from the AI
type TaskPayload struct {
	Title       string `json:"title"`
	Description string        `json:"description"`
	Subtasks    []TaskPayload `json:"subtasks"`
}

// SyncPayload represents the root JSON extracted from debate history
type SyncPayload struct {
	ProjectName string        `json:"project_name"`
	ProjectKey  string        `json:"project_key"`
	Tasks       []TaskPayload `json:"tasks"`
}

// GitlabClient handles communication with GitLab REST API.
type GitlabClient struct {
	BaseURL    string
	Token      string
	HTTPClient *http.Client
}

// NewGitlabClient creates a new client.
func NewGitlabClient(baseURL, token string) *GitlabClient {
	// Default to gitlab.com if not specified
	if baseURL == "" {
		baseURL = "https://gitlab.com"
	}
	baseURL = strings.TrimRight(baseURL, "/")
	return &GitlabClient{
		BaseURL:    baseURL,
		Token:      token,
		HTTPClient: &http.Client{},
	}
}

// SyncProject creates a project and its issues, returning the project URL.
func (c *GitlabClient) SyncProject(projectName string, tasks []TaskPayload) (string, error) {
	if c.Token == "" {
		return "", fmt.Errorf("GITLAB_TOKEN is not configured")
	}

	// 1. Create Project
	projURL := fmt.Sprintf("%s/api/v4/projects", c.BaseURL)
	projBody, _ := json.Marshal(map[string]string{
		"name":        projectName,
		"description": "Auto-generated by AI Agent",
		"visibility":  "private",
	})

	req, _ := http.NewRequest("POST", projURL, bytes.NewReader(projBody))
	req.Header.Set("PRIVATE-TOKEN", c.Token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to create gitlab project: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gitlab project creation failed (status %d): %s", resp.StatusCode, string(b))
	}

	var projResp struct {
		ID     int    `json:"id"`
		WebURL string `json:"web_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&projResp); err != nil {
		return "", fmt.Errorf("failed to decode project response: %w", err)
	}

	// 2. Create Issues
	issueURL := fmt.Sprintf("%s/api/v4/projects/%d/issues", c.BaseURL, projResp.ID)
	for _, t := range tasks {
		issueBody, _ := json.Marshal(map[string]string{
			"title":       t.Title,
			"description": t.Description,
		})
		ireq, _ := http.NewRequest("POST", issueURL, bytes.NewReader(issueBody))
		ireq.Header.Set("PRIVATE-TOKEN", c.Token)
		ireq.Header.Set("Content-Type", "application/json")

		iresp, ierr := c.HTTPClient.Do(ireq)
		if ierr == nil {
			iresp.Body.Close()
		}
	}

	return projResp.WebURL, nil
}
